name: auth

services:
  web:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_HOST: 'db'
      POSTGRES_PORT: 5432
      POSTGRES_USER_FILE: '/run/secrets/postgres_user'
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: '/run/secrets/postgres_db'
    ports:
      - 3000:3000
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

  db:
    image: 'postgres:16'
    environment:
      POSTGRES_USER_FILE: '/run/secrets/postgres_user'
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: '/run/secrets/postgres_db'
    ports:
      - 5432:5432
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

secrets:
  postgres_user:
    file: ./.secrets/postgres_user.txt
  postgres_password:
    file: ./.secrets/postgres_password.txt
  postgres_db:
    file: ./.secrets/postgres_db.txt
