name: auth

services:
  web:
    depends_on:
      - db
    build: .
    environment:
      GIN_MODE: 'release'
      PORT: 8080
    ports:
      - 8080:8080

  db:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: 'auth'
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

secrets:
  db_password:
    file: ./.secrets/db_password.txt
